FROM ubuntu:22.04
# FROM --platform=ubuntu:22.04 shivamdongre162 AS arunsingh29903
LABEL versionpython=3.10
RUN apt update -y
RUN sleep "50"
RUN echo "Hello I am after 50"
RUN apt install net-tools -y && \
apt install iputils-ping -y
# CMD [ "echo", "Hello" ]